import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Edit3,Trash2,X,RefreshCw,Receipt}from'lucide-react';
import{requireSupabase}from'./lib/supabase';
import'./billing-edit-delete.css';
const db=()=>requireSupabase();
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateStr=d=>new Date(d||Date.now()).toISOString().slice(0,10);
function Modal({title,children,close}){return <div className="bed-back"><div className="bed-modal"><div className="bed-head"><h3>{title}</h3><button onClick={close}><X size={18}/></button></div>{children}</div></div>}
function App(){const[bills,setBills]=useState([]),[patients,setPatients]=useState([]),[open,setOpen]=useState(null),[loading,setLoading]=useState(false),[q,setQ]=useState('');
 async function load(){setLoading(true);const[a,b]=await Promise.all([db().from('invoices').select('*,patients(full_name,patient_no),invoice_items(*),payments(*)').order('created_at',{ascending:false}),db().from('patients').select('id,full_name,patient_no').is('archived_at',null).order('full_name')]);setBills(a.data||[]);setPatients(b.data||[]);if(a.error)alert(a.error.message);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>bills.filter(x=>`${x.invoice_no||''} ${x.patients?.full_name||''} ${x.patients?.patient_no||''}`.toLowerCase().includes(q.toLowerCase())),[bills,q]);
 async function remove(x){const paid=(x.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);if(paid>0){alert('This bill has payments and cannot be deleted. Reverse/refund the payment first.');return}if(!confirm(`Delete bill ${x.invoice_no||''} permanently? This cannot be undone.`))return;const{error}=await db().rpc('delete_invoice_permanently',{p_invoice_id:x.id});if(error){alert(error.message);return}alert('Bill deleted successfully.');load();window.dispatchEvent(new CustomEvent('billing-changed'))}
 return <><button className="bed-launch" onClick={()=>setOpen('manager')}><Receipt size={17}/>Edit / Delete Bills</button>{open==='manager'&&<Modal title="Billing · Edit & Delete Bills" close={()=>setOpen(null)}><div className="bed-toolbar"><input placeholder="Search invoice or patient" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}><RefreshCw size={16}/>{loading?'Loading':'Refresh'}</button></div><div className="bed-list">{filtered.map(x=>{const paid=(x.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);return <div className="bed-row" key={x.id}><div><b>{x.invoice_no||'Invoice'}</b><span>{x.patients?.full_name||'—'} · {dateStr(x.created_at)}</span><span>Total {money(x.total)} · Paid {money(paid)} · Balance {money(Math.max(0,Number(x.total)-paid))}</span></div><div className="bed-actions"><button onClick={()=>setOpen({type:'edit',bill:x})}><Edit3 size={15}/>Edit</button><button className="danger" disabled={paid>0} title={paid>0?'Paid bills must be reversed/refunded before deletion':''} onClick={()=>remove(x)}><Trash2 size={15}/>Delete</button></div></div>})}{!filtered.length&&<div className="bed-empty">No bills found.</div>}</div></Modal>}{open?.type==='edit'&&<EditBill bill={open.bill} patients={patients} close={()=>setOpen('manager')} saved={()=>{setOpen('manager');load();window.dispatchEvent(new CustomEvent('billing-changed'));window.location.reload()}}/>}</>}
function EditBill({bill,patients,close,saved}){const[f,setF]=useState({patient_id:bill.patient_id,discount:bill.discount||0,tax:bill.tax||0,due_date:dateStr(bill.due_date||bill.created_at),notes:bill.notes||''}),[items,setItems]=useState((bill.invoice_items||[]).map(i=>({description:i.description||'',quantity:i.quantity||1,unit_price:i.unit_price||0}))||[]),[busy,setBusy]=useState(false);const subtotal=items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unit_price||0),0),total=Math.max(0,subtotal-Number(f.discount||0)+Number(f.tax||0)),paid=(bill.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);function upd(i,k,v){setItems(items.map((x,n)=>n===i?{...x,[k]:v}:x))}async function submit(e){e.preventDefault();setBusy(true);const{error}=await db().rpc('update_invoice_with_items',{p_invoice_id:bill.id,p_patient_id:f.patient_id,p_discount:Number(f.discount||0),p_tax:Number(f.tax||0),p_due_date:f.due_date||null,p_notes:f.notes||null,p_items:items.filter(i=>i.description).map(i=>({description:i.description,quantity:Number(i.quantity||1),unit_price:Number(i.unit_price||0)}))});if(error){alert(error.message);setBusy(false);return}alert('Bill updated successfully.');setBusy(false);saved()}return <Modal title={`Edit Bill · ${bill.invoice_no||''}`} close={close}><form className="bed-form" onSubmit={submit}><label>Patient<select value={f.patient_id} onChange={e=>setF({...f,patient_id:e.target.value})} required>{patients.map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.patient_no}</option>)}</select></label><div className="bed-note">Payments received: <b>{money(paid)}</b> · New total must not be below this amount.</div>{items.map((i,n)=><div className="bed-item" key={n}><input placeholder="Service / charge" value={i.description} onChange={e=>upd(n,'description',e.target.value)} required/><input type="number" min="1" step="0.01" value={i.quantity} onChange={e=>upd(n,'quantity',e.target.value)} required/><input type="number" min="0" step="0.01" value={i.unit_price} onChange={e=>upd(n,'unit_price',e.target.value)} required/><button type="button" onClick={()=>setItems(items.filter((_,idx)=>idx!==n))}>×</button></div>)}<button type="button" className="secondary" onClick={()=>setItems([...items,{description:'',quantity:1,unit_price:0}])}>+ Add charge</button><div className="bed-grid"><label>Discount<input type="number" min="0" step="0.01" value={f.discount} onChange={e=>setF({...f,discount:e.target.value})}/></label><label>Tax<input type="number" min="0" step="0.01" value={f.tax} onChange={e=>setF({...f,tax:e.target.value})}/></label><label>Due date<input type="date" value={f.due_date} onChange={e=>setF({...f,due_date:e.target.value})}/></label></div><label>Notes<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="bed-total">New total <b>{money(total)}</b></div><button className="primary" disabled={busy}>{busy?'Updating...':'Save Bill Changes'}</button></form></Modal>}
function mount(){if(document.getElementById('billing-edit-delete-root'))return;const el=document.createElement('div');el.id='billing-edit-delete-root';document.body.appendChild(el);createRoot(el).render(<App/>)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
