import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{FlaskConical,X,Send}from'lucide-react';
import{requireSupabase}from'./lib/supabase';
import'./lab-routing.css';
const db=()=>requireSupabase();
function Router(){const[open,setOpen]=useState(false);if(!open)return <button className="lab-route-trigger" onClick={()=>setOpen(true)}><FlaskConical size={15}/> Send to Lab</button>;return <LabModal close={()=>setOpen(false)}/>}
function LabModal({close}){const[patients,setPatients]=useState([]),[f,setF]=useState({patient_id:'',test_name:'',priority:'routine',specimen_type:'Blood',clinical_notes:''}),[busy,setBusy]=useState(false);useEffect(()=>{db().from('patients').select('id,full_name,patient_no').order('full_name').then(({data})=>setPatients(data||[]))},[]);async function submit(e){e.preventDefault();setBusy(true);const u=(await db().auth.getUser()).data.user;const{data:enc}=await db().from('encounters').select('id').eq('patient_id',f.patient_id).order('created_at',{ascending:false}).limit(1).maybeSingle();const{error}=await db().from('lab_orders').insert({...f,encounter_id:enc?.id||null,ordered_by:u?.id,status:'ordered'});setBusy(false);if(error)alert(error.message);else{alert('Laboratory order sent. It is now visible in the Laboratory queue.');close()}}
return <div className="lab-route-overlay"><div className="lab-route-modal"><div className="lab-route-head"><div><b>Send laboratory test</b><span>Order is immediately routed to the Laboratory queue.</span></div><button onClick={close}><X size={18}/></button></div><form onSubmit={submit}><label>Patient<select required value={f.patient_id} onChange={e=>setF({...f,patient_id:e.target.value})}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.patient_no}</option>)}</select></label><label>Investigation<input required placeholder="CBC, LFT, HbA1c, urine routine..." value={f.test_name} onChange={e=>setF({...f,test_name:e.target.value})}/></label><div className="lab-route-grid"><label>Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>routine</option><option>urgent</option><option>stat</option></select></label><label>Specimen<input value={f.specimen_type} onChange={e=>setF({...f,specimen_type:e.target.value})}/></label></div><label>Clinical notes<textarea value={f.clinical_notes} onChange={e=>setF({...f,clinical_notes:e.target.value})}/></label><button className="lab-route-submit" disabled={busy}><Send size={15}/>{busy?'Sending…':'Send to Laboratory'}</button></form></div></div>}
function inject(){const host=document.querySelector('.header-actions');if(!host||host.querySelector('.lab-route-root'))return;const el=document.createElement('span');el.className='lab-route-root';host.prepend(el);createRoot(el).render(<Router/>)}
const mo=new MutationObserver(inject);mo.observe(document.body,{childList:true,subtree:true});inject();