import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,Stethoscope,FlaskConical,HeartPulse,Pill,AlertTriangle,CheckCircle2,PackageCheck,Clock3}from'lucide-react';
import{requireSupabase}from'./lib/supabase';
import'./staff-nursing.css';
const db=()=>requireSupabase();
const departments=['Doctor','Laboratory','Lab Receptionist','Reception','Nursing Station','Pharmacy'];

export function StaffDirectory(){const[rows,setRows]=useState([]),[show,setShow]=useState(false),[f,setF]=useState({full_name:'',role:'doctor',designation:'',department:'Doctor',phone:'',qualification:'',registration_no:'',staff_no:''});const load=async()=>{const{data}=await db().from('profiles').select('*').order('full_name');setRows(data||[])};useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const{error}=await db().from('profiles').update({staff_no:f.staff_no||null,designation:f.designation||null,department:f.department,phone:f.phone||null,qualification:f.qualification||null,registration_no:f.registration_no||null}).eq('id',f.id);if(error)alert(error.message);else{setShow(false);load()}}return <div className="sn-page"><div className="sn-head"><div><h2>Staff Details</h2><p>Doctors, laboratory, reception, nursing station and pharmacy staff.</p></div></div><div className="sn-departments">{departments.map(x=><div className="sn-dept" key={x}>{x==='Doctor'?<Stethoscope/>:x==='Laboratory'?<FlaskConical/>:x==='Nursing Station'?<HeartPulse/>:x==='Pharmacy'?<Pill/>:<Users/>}<b>{x}</b><span>{rows.filter(r=>r.department===x).length} staff</span></div>)}</div><section className="panel"><div className="sn-tablehead"><b>Name</b><b>Role</b><b>Department</b><b>Qualification / Reg.</b><b>Phone</b><b/></div>{rows.map(r=><div className="sn-row" key={r.id}><b>{r.full_name||'—'}</b><span>{r.role}</span><span>{r.department||'—'}</span><span>{r.qualification||'—'}{r.registration_no?` / ${r.registration_no}`:''}</span><span>{r.phone||'—'}</span><button className="small" onClick={()=>{setF({...r});setShow(true)}}>Edit</button></div>)}</section>{show&&<div className="modalbackdrop"><div className="modal"><div className="modalhead"><h2>Edit staff details</h2><button className="iconbtn" onClick={()=>setShow(false)}>×</button></div><form className="formgrid" onSubmit={save}>{[['staff_no','Staff ID'],['designation','Designation'],['phone','Phone'],['qualification','Qualification'],['registration_no','Registration number']].map(([k,l])=><input key={k} placeholder={l} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<select className="wide" value={f.department||''} onChange={e=>setF({...f,department:e.target.value})}>{departments.map(x=><option key={x}>{x}</option>)}</select><button className="primary wide">Save staff details</button></form></div></div>}</div>}

export function NursingStation(){const[rows,setRows]=useState([]);const load=async()=>{const{data}=await db().from('nursing_medication_orders').select('*,patients(full_name,patient_no)').order('ordered_at',{ascending:false});setRows(data||[])};useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);async function act(r,next){const u=(await db().auth.getUser()).data.user;const fn=next==='acknowledged'?'acknowledge_nursing_medication':'administer_nursing_medication';const{error}=await db().rpc(fn,{p_order_id:r.id,p_user_id:u?.id});if(error)alert(error.message);else load()}return <div className="sn-page"><div className="sn-head"><div><h2>Nursing Station</h2><p>STAT orders arrive automatically after the doctor enters a STAT prescription.</p></div><div className="stat-badge"><AlertTriangle size={17}/> STAT QUEUE</div></div><section className="panel">{rows.length?rows.map(r=><div className={`nurse-order ${r.priority==='stat'?'stat':''}`} key={r.id}><div><b>{r.medicine_name} {r.strength||''}</b><span>{r.patients?.full_name} · {r.patients?.patient_no}</span><span>Dose: {r.dose||'—'} · Route: {r.route||'—'} · {r.frequency||'—'}</span><small>{r.instructions||''}</small></div><div className="nurse-actions"><span className={`nstatus ${r.status}`}>{r.status}</span>{r.priority==='stat'&&<span className={`nstatus ${r.pharmacy_status}`}>Pharmacy: {r.pharmacy_status}</span>}{r.status==='pending'&&<button className="small" onClick={()=>act(r,'acknowledged')}>Acknowledge</button>}{['pending','acknowledged'].includes(r.status)&&<button className="primary" disabled={r.priority==='stat'&&r.pharmacy_status!=='dispensed'} title={r.priority==='stat'&&r.pharmacy_status!=='dispensed'?'Waiting for Pharmacy to dispense':''} onClick={()=>act(r,'administered')}><CheckCircle2 size={15}/> {r.priority==='stat'&&r.pharmacy_status!=='dispensed'?'Waiting for Pharmacy':'Give medicine'}</button>}</div></div>):<div className="empty"><h3>No medication orders</h3><p>STAT medicines routed from prescriptions will appear automatically.</p></div>}</section></div>}

export function PharmacyStatBridge(){const[rows,setRows]=useState([]),[medicines,setMedicines]=useState([]),[selected,setSelected]=useState({}),[busy,setBusy]=useState({});const load=async()=>{const[{data:orders},{data:meds}]=await Promise.all([db().from('nursing_medication_orders').select('*,patients(full_name,patient_no)').eq('priority','stat').in('pharmacy_status',['pending','dispensed']).order('ordered_at',{ascending:false}),db().from('medicines').select('id,name,strength,batch_no,expiry_date,stock,unit_price').order('name')]);setRows(orders||[]);setMedicines(meds||[])};useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);async function dispense(r){const u=(await db().auth.getUser()).data.user;const medicineId=selected[r.id]||medicines.find(m=>m.name.toLowerCase()===r.medicine_name.toLowerCase()&&(m.strength||'').toLowerCase()===(r.strength||'').toLowerCase())?.id;if(!medicineId){alert('Select the matching pharmacy medicine first.');return}const qty=Number(r.quantity||1);setBusy(b=>({...b,[r.id]:true}));const{error}=await db().rpc('dispense_stat_medication',{p_order_id:r.id,p_medicine_id:medicineId,p_quantity:qty,p_user_id:u?.id});setBusy(b=>({...b,[r.id]:false}));if(error)alert(error.message);else load()}return <section className="panel pharmacy-stat"><div className="sn-head"><div><h3><PackageCheck size={18}/> Pharmacy · STAT dispensing</h3><p>Stock is deducted only when Pharmacy confirms dispense.</p></div></div>{rows.length?rows.map(r=>{const match=medicines.filter(m=>m.name.toLowerCase()===r.medicine_name.toLowerCase());return <div className="sn-row pharmacy-task" key={r.id}><div><b>{r.medicine_name} {r.strength||''}</b><span>{r.patients?.full_name} · {r.patients?.patient_no}</span><span>Qty: {r.quantity||1} · Dose: {r.dose||'—'} · Route: {r.route||'—'}</span></div><div className="pharmacy-actions">{r.pharmacy_status==='pending'?<><select value={selected[r.id]||''} onChange={e=>setSelected(s=>({...s,[r.id]:e.target.value}))}><option value="">Select stock item</option>{match.map(m=><option key={m.id} value={m.id}>{m.name} {m.strength||''} · Stock {m.stock}</option>)}</select><button className="primary" disabled={!!busy[r.id]} onClick={()=>dispense(r)}><PackageCheck size={15}/>{busy[r.id]?'Dispensing…':'Dispense STAT'}</button></>:<span className="nstatus dispensed"><CheckCircle2 size={15}/> Dispensed · Nursing ready</span>}<span className="nstatus stat"><Clock3 size={14}/> {r.status}</span></div></div>}) : <div className="empty"><h3>No STAT pharmacy tasks</h3><p>When a doctor saves a STAT medicine, Pharmacy receives a task automatically.</p></div>}</section>}

export function mountStaffNursing(){const old=document.querySelector('#staff-nursing-root');if(old)return;const root=document.createElement('div');root.id='staff-nursing-root';document.querySelector('main')?.appendChild(root);createRoot(root).render(<NursingStation/>)}
