import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,Stethoscope,FlaskConical,HeartPulse,Pill,AlertTriangle,CheckCircle2}from'lucide-react';
import{requireSupabase}from'./lib/supabase';
import'./staff-nursing.css';
const db=()=>requireSupabase();
const departments=['Doctor','Laboratory','Reception','Nursing Station','Pharmacy'];
export function StaffDirectory(){const[rows,setRows]=useState([]),[show,setShow]=useState(false),[f,setF]=useState({full_name:'',role:'doctor',designation:'',department:'Doctor',phone:'',qualification:'',registration_no:'',staff_no:''});const load=async()=>{const{data}=await db().from('profiles').select('*').order('full_name');setRows(data||[])};useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const{error}=await db().from('profiles').update({staff_no:f.staff_no||null,designation:f.designation||null,department:f.department,phone:f.phone||null,qualification:f.qualification||null,registration_no:f.registration_no||null}).eq('id',f.id);if(error)alert(error.message);else{setShow(false);load()}}return <div className="sn-page"><div className="sn-head"><div><h2>Staff Details</h2><p>Doctors, laboratory, reception, nursing station and pharmacy staff.</p></div></div><div className="sn-departments">{departments.map(x=><div className="sn-dept" key={x}>{x==='Doctor'?<Stethoscope/>:x==='Laboratory'?<FlaskConical/>:x==='Nursing Station'?<HeartPulse/>:x==='Pharmacy'?<Pill/>:<Users/>}<b>{x}</b><span>{rows.filter(r=>r.department===x).length} staff</span></div>)}</div><section className="panel"><div className="sn-tablehead"><b>Name</b><b>Role</b><b>Department</b><b>Qualification / Reg.</b><b>Phone</b><b/></div>{rows.map(r=><div className="sn-row" key={r.id}><b>{r.full_name||'—'}</b><span>{r.role}</span><span>{r.department||'—'}</span><span>{r.qualification||'—'}{r.registration_no?` / ${r.registration_no}`:''}</span><span>{r.phone||'—'}</span><button className="small" onClick={()=>{setF({...r});setShow(true)}}>Edit</button></div>)}</section>{show&&<div className="modalbackdrop"><div className="modal"><div className="modalhead"><h2>Edit staff details</h2><button className="iconbtn" onClick={()=>setShow(false)}>×</button></div><form className="formgrid" onSubmit={save}>{[['staff_no','Staff ID'],['designation','Designation'],['phone','Phone'],['qualification','Qualification'],['registration_no','Registration number']].map(([k,l])=><input key={k} placeholder={l} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<select className="wide" value={f.department||''} onChange={e=>setF({...f,department:e.target.value})}>{departments.map(x=><option key={x}>{x}</option>)}</select><button className="primary wide">Save staff details</button></form></div></div>}</div>}
export function NursingStation(){const[rows,setRows]=useState([]);const load=async()=>{const{data}=await db().from('nursing_medication_orders').select('*,patients(full_name,patient_no)').order('ordered_at',{ascending:false});setRows(data||[])};useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);async function act(r,next){const u=(await db().auth.getUser()).data.user;const fn=next==='acknowledged'?'acknowledge_nursing_medication':'administer_nursing_medication';const{error}=await db().rpc(fn,{p_order_id:r.id,p_user_id:u?.id});if(error)alert(error.message);else load()}return <div className="sn-page"><div className="sn-head"><div><h2>Nursing Station</h2><p>STAT medication orders appear here immediately.</p></div><div className="stat-badge"><AlertTriangle size={17}/> STAT QUEUE</div></div><section className="panel">{rows.length?rows.map(r=><div className={`nurse-order ${r.priority==='stat'?'stat':''}`} key={r.id}><div><b>{r.medicine_name} {r.strength||''}</b><span>{r.patients?.full_name} · {r.patients?.patient_no}</span><span>Dose: {r.dose||'—'} · Route: {r.route||'—'} · {r.frequency||'—'}</span><small>{r.instructions||''}</small></div><div className="nurse-actions"><span className={`nstatus ${r.status}`}>{r.status}</span>{r.status==='pending'&&<button className="small" onClick={()=>act(r,'acknowledged')}>Acknowledge</button>}{['pending','acknowledged'].includes(r.status)&&<button className="primary" onClick={()=>act(r,'administered')}><CheckCircle2 size={15}/> Given</button>}</div></div>):<div className="empty"><h3>No medication orders</h3><p>STAT medicines routed from prescriptions will appear automatically.</p></div>}</section></div>}
export function PharmacyStatBridge(){const[rows,setRows]=useState([]);useEffect(()=>{const load=async()=>{const{data}=await db().from('nursing_medication_orders').select('*,patients(full_name,patient_no)').eq('priority','stat').in('status',['pending','acknowledged']).order('ordered_at',{ascending:false});setRows(data||[])};load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);return <section className="panel pharmacy-stat"><h3><AlertTriangle size={18}/> STAT medicines · Nursing Station</h3>{rows.map(r=><div className="sn-row" key={r.id}><b>{r.medicine_name}</b><span>{r.patients?.full_name}</span><span>{r.dose||'—'} · {r.route||'—'}</span><span className="nstatus stat">{r.status}</span></div>)}</section>}
export function mountStaffNursing(){const old=document.querySelector('#staff-nursing-root');if(old)return;const root=document.createElement('div');root.id='staff-nursing-root';document.querySelector('main')?.appendChild(root);createRoot(root).render(<NursingStation/>)}
