import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend}from'recharts';
import{Volume2,VolumeX,MessageCircle,TrendingUp,IndianRupee,UsersRound}from'lucide-react';
import{requireSupabase}from'./lib/supabase';
import'./ui-enhancements.css';

const SOUND_KEY='clinic-sound';
let audioCtx;
function ctx(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx}
function tone(freq,duration=.06,type='sine',gain=.035){try{const c=ctx(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch{}}
function sound(kind='click'){if(localStorage.getItem(SOUND_KEY)==='off')return;if(kind==='success'){tone(660,.09);setTimeout(()=>tone(880,.13),75)}else if(kind==='critical'){tone(150,.22,'sawtooth',.06);setTimeout(()=>tone(110,.28,'sawtooth',.05),130)}else tone(520,.045)}
function SoundControl(){const[on,setOn]=useState(()=>localStorage.getItem(SOUND_KEY)!=='off');return <button className="sound-toggle"title={on?'Sound on':'Sound off'} onClick={()=>{const n=!on;setOn(n);localStorage.setItem(SOUND_KEY,n?'on':'off');if(n)sound('success')}}>{on?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{on?'Sound':'Muted'}</span></button>}
function Analytics(){const[data,setData]=useState({intake:[],revenue:[],dept:[]});useEffect(()=>{let alive=true;(async()=>{const s=requireSupabase(),start=new Date();start.setDate(start.getDate()-6);const iso=d=>d.toISOString().slice(0,10);const dates=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return iso(d)});const[p,a,pay]=await Promise.all([s.from('patients').select('created_at'),s.from('appointments').select('appointment_date,type'),s.from('payments').select('created_at,amount')]);if(!alive)return;setData({intake:dates.map(d=>({date:d.slice(5),patients:(p.data||[]).filter(x=>String(x.created_at||'').slice(0,10)===d).length})),revenue:dates.map(d=>({date:d.slice(5),revenue:(pay.data||[]).filter(x=>String(x.created_at||'').slice(0,10)===d).reduce((n,x)=>n+Number(x.amount||0),0)})),dept:Object.entries((a.data||[]).reduce((m,x)=>{const k=x.type||'General';m[k]=(m[k]||0)+1;return m},{})).sort((x,y)=>y[1]-x[1]).slice(0,6).map(([department,load])=>({department,load}))})})().catch(()=>{});return()=>{alive=false}},[]);return <section className="analytics"><div className="analytics-head"><div><span>LIVE ANALYTICS</span><h2>Hospital performance</h2><p>Recent patient intake, collected revenue and appointment load.</p></div><div className="analytics-kpis"><div><UsersRound size={16}/><b>{data.intake.reduce((n,x)=>n+x.patients,0)}</b><small>New patients</small></div><div><IndianRupee size={16}/><b>₹{data.revenue.reduce((n,x)=>n+x.revenue,0).toLocaleString('en-IN')}</b><small>Revenue</small></div><div><TrendingUp size={16}/><b>{data.dept.reduce((n,x)=>n+x.load,0)}</b><small>Appointments</small></div></div></div><div className="charts"><div className="chart-card"><h3>Patient intake</h3><ResponsiveContainer width="100%" height={220}><AreaChart data={data.intake}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Area type="monotone" dataKey="patients" fill="rgba(16,185,129,.18)" stroke="#10B981" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="chart-card"><h3>Collected revenue</h3><ResponsiveContainer width="100%" height={220}><AreaChart data={data.revenue}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={v=>`₹${Number(v).toLocaleString('en-IN')}`}/><Area type="monotone" dataKey="revenue" fill="rgba(6,182,212,.18)" stroke="#06B6D4" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="chart-card wide-chart"><h3>Department / visit-type load</h3><ResponsiveContainer width="100%" height={220}><BarChart data={data.dept}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="department"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="load" fill="#10B981" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></section>}
function shareText(el){const text=(el.innerText||'').replace(/Share via WhatsApp/g,'').replace(/\s+/g,' ').trim();return `Doctor's Clinic — record summary:\n${text}`}
function installWhatsApp(){document.querySelectorAll('.dataRow,.wf-row').forEach(el=>{if(el.querySelector('.wa-share'))return;const b=document.createElement('button');b.className='wa-share';b.title='Share via WhatsApp';b.innerHTML='<span>WhatsApp</span>';b.onclick=e=>{e.stopPropagation();sound('click');window.open('https://wa.me/?text='+encodeURIComponent(shareText(el)),'_blank','noopener,noreferrer')};el.appendChild(b)})}
function injectAnalytics(){const h=[...document.querySelectorAll('header h1')].find(x=>x.textContent==='Dashboard');if(!h)return;const main=h.closest('main');if(!main||main.querySelector('.analytics-mount'))return;const mount=document.createElement('div');mount.className='analytics-mount';main.querySelector('.content')?.appendChild(mount);createRoot(mount).render(<Analytics/>)}
function boot(){const oldAlert=window.alert;window.alert=(msg)=>{sound('critical');oldAlert(msg)};document.addEventListener('click',e=>{if(e.target.closest('button'))sound('click')},true);const header=document.querySelector('header');if(header&&!header.querySelector('.sound-toggle')){const host=document.createElement('div');header.querySelector('.header-actions')?.prepend(host);createRoot(host).render(<SoundControl/>)}const observer=new MutationObserver(()=>{installWhatsApp();injectAnalytics();});observer.observe(document.body,{subtree:true,childList:true});installWhatsApp();injectAnalytics()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
